### ISSUE TITLE
Header handling improvement

### ISSUE THREAD

**Issue by wookievx** [pheymann/typedapi#35]
There are still limitations regarding headers. Let me elaborate:
# Server.Match
Server can accept any header which name contains given string, but only its value is forwarded to the library user, which is quite frankly not very useful . Hopefully it should be quite easy to fix, i propose the following solution:
## IsHeader typeclass
A typeclass could be introduced to indicate that a specific type may represent a header. So integration with specific servers would be even better. 
**Pseudo-signature**
```scala
trait HeaderDecoder[H] {
  def parse(key: String, value: String): Either[Error, H]
}
```
## Api definition
```scala
def myApi[H: HeaderDecoder] = := myPath :> Server.Match[H]("my-hdr")
```
## Server usage
```scala
//usage with http4s
import org.http4s.Header
def implementation(headers: Set[Header]): = ???
derive[IO](myApi[Header]).from(implementation)
```
It would require only a small change to RouteExtractor.scala to work i think.
# (Proposed) Client.Headers
This change was previously rejected and is not mandatory because it can be properly handled by reimplementing integration for specific http client, question is does it need to be done this way. I think the use-case is quite common, especially in combination with **Server.Match**: service accept a specific group of headers (used for request tracing etc.) and forwards them to different services.

**Comment by pheymann** [comment]
Hi @wookievx ,
I think the example you give in this issue gives me a better picture of the problem you have. I am not a huge fan of the typeclass approach though as it:
 - fixes the http library backend already at the derive-stage (right not this happens when the endpoints are mounted)
 - makes the api declaration larger
 - the typeclass instance isn't needed at that point

It would break the assumption that the endpoint functions don't know/have to care about the underlying implementation. I would rather introduce a class `Header` which contains key and value and pass that on. 

Or is there a reason why you need the specific header class of the underlying library?

**Comment by wookievx** [comment]
You are right, this typeclass should be moved away from API definition (then it is possibly not necessary at all because framework specific implementation can handle it's own header implementation). But we should change `Set[V]` to `Map[String, V]` i suppose.

**Comment by pheymann** [comment]
I will release 0.2.0-RC3 including this change in a few minutes
